defaultEntryPoints = ["http", "https"]
[web]
address = ":8080"
  [web.auth.basic]
  users = ["admin:$apr1$NIsz4bEO$wta9en8ubHBXtA3f0k.x20"]
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
       [[entryPoints.https.tls.certificates]]
        certFile = "/traefik.crt"
        keyFile = "/traefik.key"
